### ISSUE TITLE
Incorrect results without BMI2

### ISSUE THREAD

**Issue by JeWe37** [boost-ext/mph#4] opened 2024-07-04 16:55 UTC
See https://godbolt.org/z/MTTv9bj3E

Seems to only happen when the array has four elements? The specific values of the keys don't seem to matter as much though.

**Comment by krzysztof-jusiak** [comment] 2024-07-06 15:31
Thanks @JeWe37 for reporting, the issue is now fixed, the problem was that consteval.pext and pext.nobmi were used together giving slightly different results as the nobmi2 version is based on heuristic for faster performance and may fail and/or given different results. So, there is bmi2.pext togeter with consteval.pext, and nobmi2.pext with nobmi2.consteval.pext.

**Closed by krzysztof-jusiak** 2024-07-06 15:31 UTC
